#!/bin/bash -e

if [ -e /usr/local/sti/assemble ]; then
  # old assemble location in previous php image versions
  source /usr/local/sti/assemble
else 
  source ${STI_SCRIPTS_PATH}/assemble
fi

[[ -d ./tmp ]] && chmod -R go+rw ./tmp


# comment out or remove this line
# /etc/httpd/conf.modules.d/00-base.conf:LoadModule http2_module modules/mod_http2.so
#sed -e '/mod_http2/ s/^#*/#/' -i /etc/httpd/conf.modules.d/00-base.conf

# create pv & directory
mkdir -p /httpd-coredump

# create coredumps directive file
echo "CoreDumpDirectory /httpd-coredump" > /etc/httpd/conf.d/coredumps.conf
